version: '3.8'

services:
  geobot:
    build: .
    container_name: facex_search_bot
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - PYTHONUNBUFFERED=1 
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - search_network 

  db:
    image: postgres:13
    container_name: search_bot-database
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - search_network

  web:
    container_name: facex_search_web
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - 8012:8012
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - search_network

networks:
  search_network:
    external: true